### PR TITLE
Test IR Kernel and Clean Up

### LINKED ISSUE #35: #34 changed copyright date.
#34 should be reverted of fixed.

### LINKED ISSUE #36: JupyterHub R Kernel Test does not work
Hi all,

[test_irkernel.py](https://github.com/jupyter/jupyter_kernel_test/blob/00e3f8fc1139757b1d7b52a8d0b3ff85da74b058/test_irkernel.py) does not work. R Kernel works correct. `test_execute_result` does not work. Looks like test waiting on "[1] 6" result and get just "6". Any ideas how I can fix `test_execute_result` in fastest way?

```
[korniichuk@jupyter ~]$ python3 test_ipykernel.py
/usr/lib/python3.6/site-packages/jupyter_client/manager.py:77: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
s...s.ssss..s
======================================================================
FAIL: test_execute_result (__main__.IRKernelTests) (code='1+2+3')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jupyter_kernel_test/__init__.py", line 216, in test_execute_result
    self.assertEqual(output_msgs[0]['msg_type'], 'execute_result')
AssertionError: 'display_data' != 'execute_result'
- display_data
+ execute_result
```
**Environment:**
CentOS 7.4
Linux jupyter 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.3
R 3.4.1
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.3.0)
jupyter-kernel-gateway (2.0.1)
jupyter-kernel-test (0.3)
jupyterhub (0.8.0)

### LINKED ISSUE #40: The `payload` field is optional in `execute_result`
According to the documentation, the `payload` attribute of the `execute_result` is optional but `jupyter_kernel_test` requires it.

http://jupyter-client.readthedocs.io/en/stable/messaging.html#execution-results

### LINKED ISSUE #50: Execute_result and display_data message order
As I was adding a `code_display_data` test to `xeus-python` and `xeus-cling`. I am seeing the following error:

```python
AssertionError: 'execute_result' != 'display_data'
```

It seems that xeus is sending `execute_result` before `display_data` and that `jupyter_kernel_test` is expecting `display_data` to come first. I don't *think* that the protocol imposes an order though.

### LINKED ISSUE #53: Acknowledge the kernel nudging mechanism
The kernel nudging mechanism described in https://github.com/jupyter/jupyter_client/issues/593 and implemented in notebook, jupyter_server, and jupyter_client may cause the jupyter kernel tests to fail because of the extra kernel info replies received.

### LINKED ISSUE #54: All tests are broken
Currently all the tests are failing with:
```
_________________________ ERROR at setup of IRKernelTests.test_pager _________________________

cls = <class 'test_irkernel.IRKernelTests'>

    @classmethod
    def setUpClass(cls):
        # Skip tests if it's an instance of KernelTests
        # See https://github.com/jupyter/jupyter_kernel_test/issues/7
        if cls is KernelTests:
            raise SkipTest
    
>       conn_info, km = cls.launch_kernel()
E       TypeError: cannot unpack non-iterable coroutine object

jupyter_kernel_test/__init__.py:36: TypeError
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #54, Fixes #50, Fixes #40, Fixes #36, Fixes #35, Fixes #53

### CODE REVIEW

**Comment by blink1073** [comment]
@SylvainCorlay mind taking a look at this since it closes a few of the issues you opened?

**Comment by blink1073** [comment]
I'll merge this tomorrow and make a release if there are no objections.

**Comment by SylvainCorlay** [comment]
> Fixes #54, Fixes #50, Fixes #40, Fixes #36, Fixes #35, Fixes #53

tumblr_ovvmevB5lh1rmrpdmo1_400

wow

**Comment by SylvainCorlay** [comment]
Thank you @blink1073 for reviving this effort.

**Pull request merged**
